Resources:
  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.TODO_TABLE}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: todoId
          AttributeType: S
      KeySchema:
        - AttributeName: todoId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ${self:provider.environment.INDEX_NAME}
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

      BillingMode: PAY_PER_REQUEST